local_backend: true
backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

media_folder: static/img
public_folder: /img

collections:
  - name: "news"
    label: "News"
    folder: "src/pages/news"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "news-article"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Image", name: "image", widget: image}
      - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
      - label: "Layout Content" 
        name: "layout" 
        widget: "list" 
        types: 
          - label: "Testimonial" 
            name: "testimonial" 
            widget: object 
            fields: 
              - {label: Testimonial Block, name: testimonial, widget: object, fields: [{ label: Name, name: name, widget: string, required: false}, { label: Quote, name: quote, widget: text}]}
          - label: "Column" 
            name: "column" 
            widget: object 
            fields: 
              - {label: "Column Block", name: column, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Text, name: text, widget: markdown}]}
          - label: "Full"
            name: "full"
            widget: object
            fields:
             - {label: "Full Width Block", name: full, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Text, name: text, widget: markdown}]}

  - name: "product-category"
    label: "Product Group"
    folder: "src/pages/product-category"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product-category"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "subtitle", widget: "string"}
      - {label: "Image", name: "image", widget: image}
      - {label: "USP", name: usps, widget: list, fields: [{label: USP, name: usp, widget: string}]}
      - {label: "Content Intro", name: "body", widget: "markdown"}
      - {label: "Image Gallery", name: images, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}
      - {label: "Products", name: products, widget: relation, collection: product, searchFields: [title], displayFields: [title], valueField: title, multiple: true, required: false}
      - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
      - label: "Layout Content" 
        name: "layout" 
        widget: "list" 
        types: 
          - label: "Testimonial" 
            name: "testimonial" 
            widget: object 
            fields: 
              - {label: Testimonial Block, name: testimonial, widget: object, fields: [{ label: Name, name: name, widget: string, required: false}, { label: Quote, name: quote, widget: text}]}
          - label: "Column" 
            name: "column" 
            widget: object 
            fields: 
              - {label: "Column Block", name: column, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Text, name: text, widget: markdown}]}
          - label: "Full"
            name: "full"
            widget: object
            fields:
             - {label: "Full Width Block", name: full, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Text, name: text, widget: markdown}]}

  - name: "product"
    label: "Product"
    folder: "src/pages/product"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "product"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Sub-title", name: "subtitle", widget: "string"}
      - {label: "USP", name: usps, widget: list, fields: [{label: USP, name: usp, widget: string}]}
      - {label: "Image", name: "image", widget: image}
      - {label: "Image Gallery", name: images, widget: list, fields: [{label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}]}
      - label: "Layout Content" 
        name: "layout" 
        widget: "list" 
        types: 
          - label: "Testimonial" 
            name: "testimonial" 
            widget: object 
            fields: 
              - {label: Testimonial Block, name: testimonial, widget: object, fields: [{ label: Name, name: name, widget: string, required: false}, { label: Quote, name: quote, widget: text}]}
          - label: "Column" 
            name: "column" 
            widget: object 
            fields: 
              - {label: "Column Block", name: column, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Text, name: text, widget: markdown}]}
          - label: "Full"
            name: "full"
            widget: object
            fields:
             - {label: "Full Width Block", name: full, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Text, name: text, widget: markdown}]}
      - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
  - name: "projects"
    label: "Projects"
    folder: "src/pages/projects"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "project-article"}
      - {label: "Image", name: "image", widget: image}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Intro", name: "intro", widget: "markdown"}
      - {label: "Project Feature", name: "projectfeature", widget: object, fields: [{label: "Project Image", name: "image", widget: "image"}, {label: "Name", name: "name", widget: string}, {label: "Quote", name: "quote", widget: text}]}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}

  - name: "pages"
    label: "Pages"
    files:
      - file: "src/pages/about-us/index.md"
        label: "About"
        name: "about"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "about-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Sub-title", name: "subtitle", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Image", name: "image", widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
      - file: "src/pages/team/index.md"
        label: "Team"
        name: "team"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "team-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Team Members", name: team-members, widget: list, fields: [{label: "Name", name: "name", widget: "string"},{label: "Job title", name: "jobtitle", widget: "string"},{label: "LinkedIn", name: "linkedin", widget: "string"},{label: "Interests", name: interests, widget: select, multiple: true, options: [{label: "Cycling", value: "cycling"}, {label: "Gardening", value: "gardening"}, {label: "Jiu Jitsu", value: "jiujitsu"}, {label: "Skiing", value: "skiing"}, {label: "Surfing", value: "surfing"}, {label: "Snowboarding", value: "snowboarding"}, {label: "Formula 1", value: "formula1"}, {label: "Archery", value: "archery"}, {label: "Cooking", value: "cooking"}, {label: "Football", value: "football"}, {label: "Hiking", value: "hiking"}, {label: "Church", value: "church"}, {label: "Decorating", value: "decorating"}, {label: "Climbing Wall", value: "climbing-wall"}, {label: "Golf", value: "golf"}, {label: "Knitting", value: "knitting"}, {label: "Reading", value: "reading"}, {label: "Xbox", value: "xbox"}]},{label: "Image", name: "image", widget: image},{label: "bio", name: "bio", widget: "markdown"}]}
          - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
      - file: "src/pages/videos/index.md"
        label: "Videos"
        name: "video"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "video-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Videos", name: video, widget: list, fields: [{label: "Name", name: "name", widget: "string"},{label: "Youtube video ID", name: "id", widget: "text"}]}
          - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
      - file: "src/pages/industries/index.md"
        label: "Industries"
        name: "industries"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "industries-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Sub-title", name: "subtitle", widget: "string"}
          - {label: "Intro", name: "intro", widget: "text"}
          - {label: "Image", name: "image", widget: image}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "Testimonial", name: testimonial, widget: object, fields: [{label: Name, name: name, widget: string}, {label: Quote, name: quote, widget: text}]}
          - {label: "Industries", name: industries, widget: list, fields: [{label: Name, name: name, widget: text}, {label: Image, name: image, widget: image}, {label: Alt, name: alt, widget: string}, {label: Featured, name: featured, widget: boolean, required: false}]}
          - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
      - file: "src/pages/terms-and-conditions/index.md"
        label: "Terms & Conditions"
        name: "terms-and-conditions"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "terms-and-conditions-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
      - file: "src/pages/privacy-policy/index.md"
        label: "Privacy Policy"
        name: "privacy-policy"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden", default: "privacy-policy-page"}
          - {label: "Title", name: "title", widget: "string"}
          - {label: "Body", name: "body", widget: "markdown"}
          - {label: "SEO", name: seo, widget: object, fields: [{label: Title, name: title, widget: string, required: false}, {label: Description, name: description, widget: text, required: false}]}
      